addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "4.0.2")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.8.0")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.itv" % "sbt-scalapact" % "2.3.16")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0")
