-- NDLA-208: Add revision column to support optimistic locking
ALTER TABLE learningpaths ADD COLUMN REVISION INTEGER NOT NULL DEFAULT 1;
ALTER TABLE learningsteps ADD COLUMN REVISION INTEGER NOT NULL DEFAULT 1;